# Generated by Django 3.2.10 on 2023-08-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=122)),
                ('pharmacy_name', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
